### PR TITLE
Feature/python 3.10.0

### PR DESCRIPTION
**Pull request by jklardie**

### CODE REVIEW

**Comment by masikh** [comment]
Why are these packages included in a python docker? I would expect a lean and mean python only container!

More precise: I would expect an updated pip, wheel and setup-tools that's it. All else is confusion and unneeded. This image strikes me an application specific image, not a base python image.

        unzip \
        wget \
        dnsutils \
        vim-tiny \
        net-tools \
        netcat \
        libgeos-dev \
        gdal-bin \
        postgresql-client-11 \
        libgdal20 \
        libspatialite7 \
        libfreexl1 \
        libgeotiff2 \
        libwebp-dev \
        proj-bin \
        mime-support \
        gettext \

**Comment by masikh** [comment]
Also this is strange: WORKDIR /app Why? Again application specific

**Comment by masikh** [comment]
uwsgi? Not a base python package!

**Comment by masikh** [comment]
useradd --user-group --system datapunt 

Same comment as above: This has nothing to do with a base python image. Its not generic, hence to needed, moreover unwanted!

**Comment by masikh** [comment]
I would expect an image like this, nothing more nor less

```
FROM python:3.10.0-buster

MAINTAINER datapunt@amsterdam.nl

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=on 
RUN pip install --upgrade pip wheel setup-tools
```

Note the PIP_NO_CHACHE_DIR is ON not OFF. There's hardly any use for python install packages cache in a docker container

**Comment by jklardie** [comment]
As discussed, this was never and is not intended as a lean python base image for generic use. It is a base image specifically used for applications that we run on our current infra, that works well for us. Changing anything in the packages is impossible due to its use in many legacy applications. 

These base images should not be blindly used when migrating to a new infra, as it was never intended to be a generic base image.

**Pull request closed without merging**
